services:
  - type: web
    name: family-tree
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
